home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('milestone_17/', views.milestone_17, name='milestone_17'),
]

new_c_2319/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from register import views as v

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('posts.urls')),
    path('register/' , v.register , name = 'register'),
    path('', include('django.contrib.auth.urls')),
    url(r'^account/', include('register.urls')),
    path('', include('sendemail.urls')), # new

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views
from .views import PostDetailView, PostListView, ForSaleListView
from django.urls import path , re_path


urlpatterns = [
    url('add/post/$' , views.add_post , name='add_post'),
    re_path(r'^(?P<pk>\d+)/$', PostDetailView.as_view(), name='post_detail'),
    path('', PostListView.as_view(), name='post_list'),
    url(r'^edit/(?P<pk>\d+)/$' , views.edit_post, name = 'edit_post'),
    path('forsale' , ForSaleListView.as_view(), name='for_sale'),
    url(r'^delete/(?P<pk>\d+)/$' , views.delete_post, name = 'delete_post'),
    #re_path(r'^(?P<pk>\d+)/$', views.contact_p, name="contact_p"),
    ]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)
CATEGORY = (
    (0,"Electronic"),
    (1,"Furniture"),
    (2,"Major Appliance"),
    (3,"Kitchen"),
    (4,"Books"),
    (5,"Motors"),
    (6,"Music"),
    (7,"Other")
)
CONDITION = {
    (0,"Brand New"),
    (1, "Used - Like New"),
    (2, "Used - Good"),
    (3, "Used - Poor Condidtion"),
    (4, "Used - Not Usable")
}

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post" , null=True)
    title = models.CharField(max_length=50)
    body = models.TextField(null=True, max_length=300)
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    category = models.IntegerField(choices=CATEGORY, default=0)
    cover = models.ImageField(upload_to='images/', null=True , blank=True)
    condition = models.IntegerField(choices=CONDITION , default = 4)
    price = models.DecimalField(max_digits=11 , decimal_places=2, default=Decimal(0.00), null=True ,blank=True, validators=[MinValueValidator(0.00) , MaxValueValidator(9999999999)])
    publish = models.IntegerField(choices=STATUS, default=0)

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title' , 'body' , 'price' , 'condition' , 'category' , 'cover', 'publish']

posts/views.py
from django.shortcuts import render
from .forms import PostForm
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.generic import ListView, DetailView
from .models import Post
from django.core.mail import send_mail
from django.conf import settings
from .filters import PostFilter
from django.contrib import messages


# Create your views here.
def add_post(request):

    if request.method == "POST":
        # form = PostForm(request.POST)
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid() :
            post_item = form.save(commit=False)
            # a = post_item.save()
            n = form.cleaned_data["title"]
            m = form.cleaned_data["cover"]
            a = form.cleaned_data["category"]
            b = form.cleaned_data["condition"]
            c = form.cleaned_data["price"]
            d = form.cleaned_data["body"]
            e = form.cleaned_data["publish"]
            t = Post(title=n, body=d , price=c, condition=b , category=a, cover=m, publish=e)
            t.save()
            request.user.post.add(t)
            messages.success(request, 'Your new item was created successfully!', extra_tags='add')
            return redirect('/post/')
    else:
        form = PostForm()
    return render (request, '../templates/post_form.html' , {'form' : form})


class PostDetailView(DetailView):
        model = Post
        template_name = '../templates/post_detail.html'

class PostListView(ListView):
    model = Post
    template_name = '../templates/post_list.html'


class ForSaleListView(ListView):
    model = Post
    template_name = '../templates/forsale.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET , queryset = self.get_queryset())
        return context


def edit_post(request , pk=None):
    item = get_object_or_404(Post , pk=pk)
    form = PostForm(request.POST or None , request.FILES or None ,instance=item)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your item was successfully updated!', extra_tags='edit')
        return redirect('/post/' + str(pk) + '/')
    #return render (request, 'post/post_form.html' , {'form' : form})
    return render (request, '../templates/post_form.html' , {'form' : form})

def delete_post(request, pk=None):
    item = get_object_or_404(Post , pk=pk)
    form = PostForm(request.POST or None , instance=item)
    item.delete()
    messages.error(request, 'Your item was successfully deleted!', extra_tags='delete')
    return redirect('/post/')
    # return render (request, '../templates/post_list.html' , {'form' : form})


#def delete_post(request, pk=None):
#    item = get_object_or_404(Post , pk=pk)
#    form = PostForm(request.POST or None , instance=item)
#    if request.method == "POST":
#        item.delete()
#        return redirect('/post/')
#    context = { 'item' : item}
#    return render (request, '../templates/post_list.html' , context)

#**    
def contact_p(request, pk=None):
    item = get_object_or_404(Post , pk=pk)
    post_e = post.pk
    if request.method == "POST":
        message_e = request.POST['message']
        message = 'h'
        send_mail(
          'A new message from a futre buyer',
          message,
          settings.EMAIL_HOST_USER, 
          [request.user.email],
          fail_silently = False)
    return redirect('/post/')

posts/templates/forsale.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
<br><br><br>
{% if user.is_authenticated %}
  <h1>Items for sale</h1><br>
  <div class="card" id="forsale">
  <div class="col-sm-12">
    <form method="GET">

       <div class="row">
        <h4>&nbspTitle Contains&nbsp</4>
        {{ filter.form.title__icontains}}
        <div class="btt-box">
            <button type="submit" class="btn btn-success" id="filter_but">Search</button>
            <a href="#demo" class="btn btn-info" data-toggle="collapse" id="filter_but">Advanced Search</a>
            <a href="{% url 'for_sale' %}" class="btn btn-danger" id="filter_but">Clear Filter</a>
       </div>
        <div id="demo" class="collapse">
            <h4>Category&nbsp</4>
            {{ filter.form.category}}
            <h4><br>Price contains&nbsp</4>
            {{ filter.form.price__icontains}}
            <h4><br>Condition&nbsp</4>
            {{ filter.form.condition}}
        </div>
        </div>
    </form>
  </div>
  </div>


    <div class="center " id="cont_item">
        <div class="row">
            {% for post in filter.qs %}
                {% if post.publish == 1 %}
                    <div class="col-sm-4 card" id="indi_item">
                        {% if post.cover %}
                            <a href="{{ post.pk }}"><img src="{{ post.cover.url}}" alt="{{ post.title }}" id="item-img"></a>
                        {% else %}
                            <a href="{{ post.pk }}"><img src="/media/images/no-image-available-icon-6.jpg" alt="{{ post.title }}" id="item-img"></a>
                        {% endif %}
                        <div class="title_under_img">
                            <a href="{{ post.pk }}"><span id="element1">{{ post.title }}</span></a>
                        </div>
                        <div class="dis_under_title">
                            <a href="{{ post.pk }}"><span id="span_body">{{ post.body }}</span></a>
                        </div>
                        <div class="price_under_dis">
                            {% if post.price == None %}
                                <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;0</h5>
                            {% else %}
                                <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;{{ post.price }}</h5>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <br><br><br>


{% else %}
  <p>You are not allowed to see this list</p>
  <meta http-equiv = "refresh" content = "2"; url ='/post' />
{% endif %}
{% endblock %}

posts/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>
{% if user.is_authenticated and post.publish == 1 or user == post.user%}
    {% if messages %}
        {% for message in messages %}
            {% if "edit" in message.tags %}
                <div class="alert alert-success" role="edit">
                <p class="{{ message.tags }}" id="message-center">{{ message }}</p>
            {% elif "send" in message.tags %}
                <div class="alert alert-info" role="send">
                <p class="{{ message.tags }}" id="message-center">{{ message }}</p>
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}

<div class="container">
        <div class="center">
            <div class="card mb-4">
                <div class="card-body">
                    <h1>{{ object.title }}</h1>
                    <br>
                        <div class="same-line-img"><br><br>
                            {% if object.cover %}
                            <img src="{{ object.cover.url}}" alt="{{ object.title }}" >
                            {% else %}
                            <img src="/media/images/no-image-available-icon-6.jpg" >
                            {% endif %}        
                        </div>
                        <div class="col-sm-6">
                            <h3>Description:</h3>
                            <h5 class="pt-6-half" class="card-text text-muted h6">&nbsp{{ object.body }}</h5>
                        </div><br>                    
                        <div class="col-sm-6">
                            <div id="same-line-1">
                                <h3>Price:</h3>
                            </div>
                            <div id="same-line-2">
                                {% if object.price == None %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;0</h5>
                                {% else %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;{{ object.price }}</h5>
                                {% endif %}
                            </div>
                        </div><br> 
                        <div class="col-sm-6">
                            <div id="same-line-1">
                                <h3>Condition:<h3>
                            </div>
                            <div id="same-line-2">
                                {% if object.get_condition_display == 'Used - Not Usable' %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6"><font color="red">{{ object.get_condition_display }}</font></h5>
                                {% elif object.get_condition_display == 'Used - working' %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6"><font color="#b38f00">{{ object.get_condition_display }}</font></h5>
                                {% elif object.get_condition_display == 'Brand New' %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6"><font color="green">{{ object.get_condition_display }}</font></h5>
                                {% elif object.get_condition_display == 'Used - Like New' %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6"><font color="#0099cc">{{ object.get_condition_display }}</font></h5>
                                {% elif object.get_condition_display == 'Used - Good' %}
                                    <h5 class="pt-6-half" class="card-text text-muted h6"><font color="##9900cc">{{ object.get_condition_display }}</font></h5>
                                {% endif %}
                            </div>
                        </div><br> 
                        <div class="col-sm-6">
                            <div id="same-line-1">
                                <h3>Category:</h3>
                            </div>
                            <div id="same-line-2">
                                <h5 class="pt-6-half" class="card-text text-muted h6">{{ object.get_category_display }}</h5>
                            </div>
                        </div><br>
                        {% if user == post.user %}
                            <div class="col-sm-6">
                                <div id="same-line-1">
                                    <h3>Publish:</h3>
                                </div>
                                <div id="same-line-2">
                                    <h5 class="pt-6-half" class="card-text text-muted h6">{{ object.get_publish_display }}</h5>
                                </div>
                            </div><br> 
                        {% endif %}
                        <br><br><br>
                        <div class="col-sm-12">
                            {% if user == post.user %}
                                <a type="button" class="btn btn-outline-success" href="{% url 'edit_post' post.pk %}">Edit</a>
                            <!-- <button type="button" class="btn btn-danger btn-rounded btn-sm my-0" href="{% url 'delete_post' post.pk %}">Delete</button> -->
                                <a type="button" class="btn btn-outline-danger" href="{% url 'delete_post' post.pk %}">Delete</a>
                            {% else %}
                                <a type="button" class="btn btn-outline-success" href="{% url 'email' post.pk %}">Send a message</a>
                            {% endif %}
                            <button onclick="window.location.href='https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri}}'" class="btn btn-outline-primary">
                                Facebook
                            </button>
                            <button onclick="window.location.href='https://twitter.com/home?status=Check%20out%20my%20post%20on%20Collegemarket!%20{{ request.build_absolute_uri}}'" class="btn btn-outline-primary">
                                Twitter
                            </button>
                            <button onclick="window.location.href='https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri}}&title=Be%20first%20%7C%20Join%20Collegemarket&summary=Check%20out%20my%20post%20on%20Collegemarket!%20 &source={{ request.build_absolute_uri}}'" class="btn btn-outline-primary">
                                Linkedin
                            </button>
                        </div><br> 
                </div>
            </div>
        </div>
</div>



{% else %}
    <h3>You are not allowed to see this post</h3><br>
    <h1>Redirect...</h1>
    <meta http-equiv = "refresh" content = "2; url = {% url 'home' %}" />
{% endif %}

{% endblock %}

posts/templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}

<div class="field_wrapper">
  {{ form.title | as_crispy_field }}
  <h6 id="less_char">*Must be equal or less than 50 characters</h6>
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  {{ form.body | as_crispy_field}}
  <h6 id="less_char">*Must be equal or less than 300 characters</h6>
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  <label fpr="{{ form.price.id_for_label }}"></label>
  {{ form.price | as_crispy_field}}
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  <label fpr="{{ form.condition.id_for_label }}"></label>
  {{ form.condition | as_crispy_field}}
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  <label fpr="{{ form.category.id_for_label }}"></label>
  {{ form.category | as_crispy_field}}
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  {{ form.cover | as_crispy_field}}
  <label method="POST" enctype="multipart/form-data" fpr="{{ form.cover.id_for_label }}"></label>
</div>
<br>

<div class="field_wrapper">
  <!-- {{ form.non_field_errors }} -->
  <label fpr="{{ form.publish.id_for_label }}"></label>
  {{ form.publish | as_crispy_field}}
</div>

<button class="btn btn-success" type="submit">Save</button>
</form>

{% endblock %}

posts/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<br><br><br>
{% if user.is_authenticated %}
    {% if messages %}
        {% for message in messages %}
            {% if "add" in message.tags %}
                <div class="alert alert-success" role="add">
                <p class="{{ message.tags }}" id="message-center">{{ message }}</p>
            {% elif "delete" in message.tags %}
                <div class="alert alert-danger" role="delete">
                <p class="{{ message.tags }}" id="message-center">{{ message }}</p>
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}

    <h1>My Items</h1>
        <div class="center " id="cont_item">
            <div class="row">
            {% for post in user.post.all %}
                <div class="col-sm-4 card" id="indi_item">
                    {% if post.cover %}
                        <a href="{{ post.pk }}"><img src="{{ post.cover.url}}" alt="{{ post.title }}" id="item-img"></a>
                    {% else %}
                        <a href="{{ post.pk }}"><img src="/media/images/no-image-available-icon-6.jpg" alt="{{ post.title }}" id="item-img"></a>
                    {% endif %}
                    <div class="title_under_img">
                        <a href="{{ post.pk }}"><span id="element1">{{ post.title }}</span></a>
                    </div>
                    <div class="dis_under_title">
                        <a href="{{ post.pk }}"><span id="span_body">{{ post.body }}</span></a>
                    </div>
                    <div class="price_under_dis">
                        {% if post.price == None %}
                            <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;0</h5>
                        {% else %}
                            <h5 class="pt-6-half" class="card-text text-muted h6 pt-6-half">&#36;{{ post.price }}</h5>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <br><br><br>
  



{% else %}
  <p>You are not allowed to see this list</p>
  <meta http-equiv = "refresh" content = "2"; url ='/post' />
{% endif %}
{% endblock %}